version: "3.9"

services:
  yolo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PIP_NO_CACHE_DIR: "off"
      PIP_CACHE_DIR: "/tmp/pip-cache"
